### ISSUE TITLE
this repo should be deprecated

### ISSUE THREAD

**Issue by silky** [tweag/servant-oauth2-example#3]
this work is basically superceded by https://github.com/tweag/servant-oauth2 ; it's probably a bit confusing having it here. should be easy to mark is as archived and update the readme to point to the new repo.

**Comment by silky** [comment]
( note also that the readme hints to a blog post which was never published. )

**Comment by aspiwack** [comment]
Sorry for the late reply. @silky I gave you maintainer right on this repo. Can you do the change that you think are needed? When you're done, I'll archive the repository.

**Comment by silky** [comment]
i'll leave this to you @aspiwack .
